import {MigrationInterface, QueryRunner} from "typeorm";

export class fakeTweets1642905309680 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            insert into tweet ("userId", "textContent", "createdAt") values (27, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2021-07-18T15:40:56Z');
            insert into tweet ("userId", "textContent", "createdAt") values (13, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2021-10-15T10:08:48Z');
            insert into tweet ("userId", "textContent", "createdAt") values (17, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2021-03-16T21:10:39Z');
            insert into tweet ("userId", "textContent", "createdAt") values (15, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2021-04-29T12:16:22Z');
            insert into tweet ("userId", "textContent", "createdAt") values (17, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2022-01-01T03:10:14Z');
            insert into tweet ("userId", "textContent", "createdAt") values (16, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2021-06-19T12:09:53Z');
            insert into tweet ("userId", "textContent", "createdAt") values (9, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2021-04-26T18:34:43Z');
            insert into tweet ("userId", "textContent", "createdAt") values (4, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2021-12-04T04:50:35Z');
            insert into tweet ("userId", "textContent", "createdAt") values (2, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2020-12-24T16:04:24Z');
            insert into tweet ("userId", "textContent", "createdAt") values (16, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2020-12-11T05:54:16Z');
            insert into tweet ("userId", "textContent", "createdAt") values (7, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2021-07-02T07:46:18Z');
            insert into tweet ("userId", "textContent", "createdAt") values (22, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2021-10-15T19:22:54Z');
            insert into tweet ("userId", "textContent", "createdAt") values (24, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2021-07-14T14:02:06Z');
            insert into tweet ("userId", "textContent", "createdAt") values (13, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2021-07-12T09:43:41Z');
            insert into tweet ("userId", "textContent", "createdAt") values (27, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2021-03-30T20:04:05Z');
            insert into tweet ("userId", "textContent", "createdAt") values (29, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2021-04-29T04:23:30Z');
            insert into tweet ("userId", "textContent", "createdAt") values (1, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2021-10-16T20:39:28Z');
            insert into tweet ("userId", "textContent", "createdAt") values (2, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2021-12-28T10:51:07Z');
            insert into tweet ("userId", "textContent", "createdAt") values (9, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2021-04-21T21:40:07Z');
            insert into tweet ("userId", "textContent", "createdAt") values (13, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2021-02-09T10:55:23Z');
            insert into tweet ("userId", "textContent", "createdAt") values (3, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2021-12-18T14:29:04Z');
            insert into tweet ("userId", "textContent", "createdAt") values (27, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2021-11-19T09:46:31Z');
            insert into tweet ("userId", "textContent", "createdAt") values (23, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2021-12-21T17:34:02Z');
            insert into tweet ("userId", "textContent", "createdAt") values (24, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2021-11-23T14:52:38Z');
            insert into tweet ("userId", "textContent", "createdAt") values (6, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2021-11-19T16:55:20Z');
            insert into tweet ("userId", "textContent", "createdAt") values (12, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2021-02-26T23:29:33Z');
            insert into tweet ("userId", "textContent", "createdAt") values (12, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2020-12-30T19:18:08Z');
            insert into tweet ("userId", "textContent", "createdAt") values (9, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2021-02-09T03:47:06Z');
            insert into tweet ("userId", "textContent", "createdAt") values (13, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2021-06-19T09:00:10Z');
            insert into tweet ("userId", "textContent", "createdAt") values (12, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2021-12-18T19:32:10Z');
            insert into tweet ("userId", "textContent", "createdAt") values (2, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2021-09-13T00:04:00Z');
            insert into tweet ("userId", "textContent", "createdAt") values (6, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2021-12-11T10:55:52Z');
            insert into tweet ("userId", "textContent", "createdAt") values (13, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2021-01-10T21:40:15Z');
            insert into tweet ("userId", "textContent", "createdAt") values (22, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2021-08-29T15:50:47Z');
            insert into tweet ("userId", "textContent", "createdAt") values (3, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2021-05-19T11:28:14Z');
            insert into tweet ("userId", "textContent", "createdAt") values (13, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2021-10-12T04:52:15Z');
            insert into tweet ("userId", "textContent", "createdAt") values (3, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2021-02-02T21:27:22Z');
            insert into tweet ("userId", "textContent", "createdAt") values (5, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2021-09-19T01:33:09Z');
            insert into tweet ("userId", "textContent", "createdAt") values (3, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2021-09-07T17:01:06Z');
            insert into tweet ("userId", "textContent", "createdAt") values (3, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2020-12-17T14:42:22Z');
            insert into tweet ("userId", "textContent", "createdAt") values (28, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2021-02-24T02:17:39Z');
            insert into tweet ("userId", "textContent", "createdAt") values (5, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2020-12-23T12:41:37Z');
            insert into tweet ("userId", "textContent", "createdAt") values (30, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2021-01-15T17:34:05Z');
            insert into tweet ("userId", "textContent", "createdAt") values (3, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2021-10-21T13:10:39Z');
            insert into tweet ("userId", "textContent", "createdAt") values (8, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2021-08-28T05:26:30Z');
            insert into tweet ("userId", "textContent", "createdAt") values (17, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2021-02-08T19:05:58Z');
            insert into tweet ("userId", "textContent", "createdAt") values (22, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2021-07-28T12:13:51Z');
            insert into tweet ("userId", "textContent", "createdAt") values (23, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2021-12-15T10:11:13Z');
            insert into tweet ("userId", "textContent", "createdAt") values (27, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2021-11-25T16:18:48Z');
            insert into tweet ("userId", "textContent", "createdAt") values (28, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2021-12-04T21:48:56Z');
            insert into tweet ("userId", "textContent", "createdAt") values (14, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2021-01-18T09:22:42Z');
            insert into tweet ("userId", "textContent", "createdAt") values (31, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2020-12-11T03:49:33Z');
            insert into tweet ("userId", "textContent", "createdAt") values (4, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2021-04-23T15:40:30Z');
            insert into tweet ("userId", "textContent", "createdAt") values (1, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2021-09-24T03:05:05Z');
            insert into tweet ("userId", "textContent", "createdAt") values (31, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2020-12-15T09:12:39Z');
            insert into tweet ("userId", "textContent", "createdAt") values (25, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2021-04-06T20:27:38Z');
            insert into tweet ("userId", "textContent", "createdAt") values (29, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2021-04-14T23:59:21Z');
            insert into tweet ("userId", "textContent", "createdAt") values (4, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2021-05-02T09:56:25Z');
            insert into tweet ("userId", "textContent", "createdAt") values (7, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2020-12-18T16:33:41Z');
            insert into tweet ("userId", "textContent", "createdAt") values (6, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2021-05-30T03:18:34Z');
            insert into tweet ("userId", "textContent", "createdAt") values (28, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2021-01-01T08:26:18Z');
            insert into tweet ("userId", "textContent", "createdAt") values (6, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-01-06T13:28:31Z');
            insert into tweet ("userId", "textContent", "createdAt") values (10, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2021-05-08T01:55:42Z');
            insert into tweet ("userId", "textContent", "createdAt") values (9, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2021-08-18T09:59:02Z');
            insert into tweet ("userId", "textContent", "createdAt") values (27, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2021-11-26T06:04:46Z');
            insert into tweet ("userId", "textContent", "createdAt") values (27, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2021-10-03T20:31:06Z');
            insert into tweet ("userId", "textContent", "createdAt") values (5, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2021-07-21T11:56:58Z');
            insert into tweet ("userId", "textContent", "createdAt") values (16, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2021-12-27T02:07:48Z');
            insert into tweet ("userId", "textContent", "createdAt") values (30, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2021-10-03T10:02:51Z');
            insert into tweet ("userId", "textContent", "createdAt") values (29, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2021-07-09T17:38:39Z');
            insert into tweet ("userId", "textContent", "createdAt") values (28, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2021-07-31T22:07:42Z');
            insert into tweet ("userId", "textContent", "createdAt") values (14, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2021-04-08T04:02:12Z');
            insert into tweet ("userId", "textContent", "createdAt") values (29, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2021-03-30T21:18:13Z');
            insert into tweet ("userId", "textContent", "createdAt") values (8, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2022-01-19T19:13:52Z');
            insert into tweet ("userId", "textContent", "createdAt") values (7, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2020-12-29T05:01:09Z');
            insert into tweet ("userId", "textContent", "createdAt") values (26, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2021-11-05T12:19:57Z');
            insert into tweet ("userId", "textContent", "createdAt") values (7, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2021-01-25T07:13:26Z');
            insert into tweet ("userId", "textContent", "createdAt") values (29, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2021-11-02T14:35:29Z');
            insert into tweet ("userId", "textContent", "createdAt") values (31, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2021-07-02T20:56:26Z');
            insert into tweet ("userId", "textContent", "createdAt") values (30, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2021-01-15T22:49:22Z');
            insert into tweet ("userId", "textContent", "createdAt") values (11, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2021-06-19T20:41:43Z');
            insert into tweet ("userId", "textContent", "createdAt") values (17, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2021-02-01T09:24:51Z');
            insert into tweet ("userId", "textContent", "createdAt") values (17, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2021-05-25T01:03:10Z');
            insert into tweet ("userId", "textContent", "createdAt") values (29, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2021-04-07T03:58:19Z');
            insert into tweet ("userId", "textContent", "createdAt") values (22, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2022-01-15T17:17:42Z');
            insert into tweet ("userId", "textContent", "createdAt") values (4, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2021-08-09T07:52:21Z');
            insert into tweet ("userId", "textContent", "createdAt") values (24, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2021-03-30T19:46:42Z');
            insert into tweet ("userId", "textContent", "createdAt") values (12, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2021-03-01T22:20:58Z');
            insert into tweet ("userId", "textContent", "createdAt") values (6, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2021-12-28T16:42:26Z');
            insert into tweet ("userId", "textContent", "createdAt") values (23, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2021-09-01T01:26:53Z');
            insert into tweet ("userId", "textContent", "createdAt") values (29, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2021-01-23T21:55:19Z');
            insert into tweet ("userId", "textContent", "createdAt") values (29, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2021-11-15T01:47:02Z');
            insert into tweet ("userId", "textContent", "createdAt") values (25, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2021-12-29T10:35:10Z');
            insert into tweet ("userId", "textContent", "createdAt") values (3, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2021-08-14T03:36:46Z');
            insert into tweet ("userId", "textContent", "createdAt") values (13, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-01-11T16:44:25Z');
            insert into tweet ("userId", "textContent", "createdAt") values (11, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2021-02-19T13:09:00Z');
            insert into tweet ("userId", "textContent", "createdAt") values (6, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2021-02-19T14:21:39Z');
            insert into tweet ("userId", "textContent", "createdAt") values (26, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2021-05-30T14:03:58Z');
            insert into tweet ("userId", "textContent", "createdAt") values (17, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-01-06T21:48:51Z');
            insert into tweet ("userId", "textContent", "createdAt") values (7, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2021-02-13T13:42:20Z');
        `)
    }

    public async down(__: QueryRunner): Promise<void> {
    }

}
